server:
  port: 8082

spring:
  application:
    name: ORDER-SERVICE
  config:
    import: optional:configserver:http://localhost:9296
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
